server:
  port: 8080
spring:
  application:
    name: decryptor
  profiles:
    active: dev
  main:
    banner-mode: off
  devtools:
    add-properties: false
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric
  server:
    port: 8085
logging:
  level:
    .: INFO
    org.springframework: INFO
    ru.devstend: DEBUG

# App prors
recipientId: someRecipient

encrypt:
  recipientId: ${recipientId}
  merchantPublicKey: "BOdoXP+9Aq473SnGwg3JU1aiNpsd9vH2ognq4PtDtlLGa3Kj8TPf+jaQNPyDSkh3JUhiS0KyrrlWhAgNZKHYF2Y="
  signingEcV1PrivateKey: "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgZj/Dldxz8fvKVF5OTeAtK6tY3G1McmvhMppe6ayW6GahRANCAAQ9icfBLy56BYB7BC2XGLOYsXKfAdzFFPU8rTtwMDr8LixetUjVLNkJTHxTxLQuMytPqKt39Vbtt7czPq3+yu1F"

decrypt:
  recipientId: ${recipientId}
  verifyingPublicKeysJson: "ewogICJrZXlzIjogWwogICAgewogICAgICAia2V5VmFsdWUiOiAiTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFUFluSHdTOHVlZ1dBZXdRdGx4aXptTEZ5bndIY3hSVDFQSzA3Y0RBNi9DNHNYclZJMVN6WkNVeDhVOFMwTGpNclQ2aXJkL1ZXN2JlM016NnQvc3J0UlE9PSIsCiAgICAgICJwcm90b2NvbFZlcnNpb24iOiAiRUN2MSIKICAgIH0sCiAgICB7CiAgICAgICJrZXlWYWx1ZSI6ICJNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUUvMSszSEJWU2JkditqN05hQXJkZ015b1NBTTQzeVJ5ZHpxZGcxVHhvZFN6QTk2RGo0TWMxRWlLcm94eHVuYXZWSXZkeEduSmVGVmlUekZ2ekZSeHlDdz09IiwKICAgICAgImtleUV4cGlyYXRpb24iOiAiMTczMTA2OTMwMTg1NiIsCiAgICAgICJwcm90b2NvbFZlcnNpb24iOiAiRUN2MiIKICAgIH0sCiAgICB7CiAgICAgICJrZXlWYWx1ZSI6ICJNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVOWHZZcXhENVdheUtZaHVYUWV2ZEdkTEE4aWZWNExzUlMydUt2Rm84d3d5aXdnUUhCOURpS3pHNlQvUDFGdTlCbDd6V3kvc2U1RHk0d2sxbUpvUHV4Zz09IiwKICAgICAgImtleUV4cGlyYXRpb24iOiAiMTczMTA2OTMwMTg2NiIsCiAgICAgICJwcm90b2NvbFZlcnNpb24iOiAiRUN2MlNpZ25pbmdPbmx5IgogICAgfQogIF0KfQ=="
  merchantPrivateKey: "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgCPSuFr4iSIaQprjjchHPyDu2NXFe0vDBoTpPkYaK9dehRANCAATnaFz/vQKuO90pxsINyVNWojabHfbx9qIJ6uD7Q7ZSxmtyo/Ez3/o2kDT8g0pIdyVIYktCsq65VoQIDWSh2Bdm"
  alternateMerchantPrivateKey: "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgOUIzccyJ3rTx6SVmXrWdtwUP0NU26nvc8KIYw2GmYZKhRANCAAR5AjmTNAE93hQEQE+PryLlgr6Q7FXyNXoZRk+1Fikhq61mFhQ9s14MOwGBxd5O6Jwn/sdUrWxkYk3idtNEN1Rz"